import json
from pathlib import Path

from api_testing_agent.config import Settings
from api_testing_agent.core.request_understanding_service import (
    ResolvedPlan,
    UnderstandingResult,
)
from api_testing_agent.core.models import TestType
from api_testing_agent.tasks.orchestrator import TestOrchestrator


class FakeUnderstandingServiceSpecificImage:
    def understand(
        self,
        raw_text: str,
        *,
        forced_target_name: str,
        operation_hints: list[dict],
    ):
        plan = ResolvedPlan(
            target_name=forced_target_name,
            tags=[],
            methods=[],
            paths=["/img"],
            test_types=[
                TestType.POSITIVE,
                TestType.MISSING_REQUIRED,
                TestType.INVALID_TYPE_OR_FORMAT,
                TestType.UNAUTHORIZED,
                TestType.NOT_FOUND,
            ],
            ignore_fields=[],
            limit_endpoints=50,
        )
        return UnderstandingResult(
            original_text=raw_text,
            canonical_command=f"test target {forced_target_name} /img POST positive unauthorized not_found missing invalid",
            plan=plan,
            explanation=f"Đã xác định target là '{forced_target_name}' và đã match đúng chức năng cụ thể: POST /img.",
        )


class FakeAITestCaseAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def generate_for_operation(self, context):
        from api_testing_agent.core.ai_testcase_models import AITestCaseDraft, AITestCaseDraftList

        op = context["operation"]
        return AITestCaseDraftList(
            cases=[
                AITestCaseDraft(
                    test_type="positive",
                    description=f"Positive case for {op['method']} {op['path']}",
                    reasoning_summary="Generated by fake AI agent",
                    expected_status_codes=[200],
                )
            ]
        )


class FakeTargetResolutionAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def decide(self, *, raw_text: str, available_targets: list[str]):
        from api_testing_agent.core.target_resolution_models import TargetCandidate, TargetResolutionDecision

        return TargetResolutionDecision(
            mode="ask_user",
            selected_target=None,
            candidates=[
                TargetCandidate(name="hello_work", reason="closest"),
                TargetCandidate(name="hello_world", reason="closest"),
                TargetCandidate(name="hello_world_love", reason="closest"),
            ],
            question="Bạn muốn test chức năng sinh ảnh của target nào?",
            reason="Có nhiều target gần giống nhau nên cần user chọn.",
        )


class FakeScopeResolutionAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name


class FakeFeedbackScopeAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def decide(self, *, feedback_text: str, target_name: str, all_operation_hints: list[dict], current_scope_hints: list[dict]):
        from api_testing_agent.core.feedback_scope_models import FeedbackScopeDecision

        lowered = feedback_text.lower()

        if "thêm chức năng yt và fb" in lowered:
            return FeedbackScopeDecision(
                action_mode="add_specific",
                matched_paths=["/YT", "/FB"],
                reason="User wants to add YT and FB.",
            )

        if "bỏ yt với fb đi" in lowered:
            return FeedbackScopeDecision(
                action_mode="remove_specific",
                matched_paths=["/YT", "/FB"],
                reason="User wants to remove YT and FB.",
            )

        return FeedbackScopeDecision(
            action_mode="keep",
            reason="No scope change.",
        )


def test_feedback_can_add_and_remove_scope(tmp_path: Path):
    spec_path = tmp_path / "openapi.yaml"
    spec_path.write_text(
        """
openapi: 3.0.0
info:
  title: Demo API
  version: 1.0.0

paths:
  /img:
    post:
      operationId: image_generate_img_post
      summary: Generate image
      responses:
        "200":
          description: OK
  /FB:
    post:
      operationId: fb_get_content_FB_post
      summary: Generate Facebook content
      responses:
        "200":
          description: OK
  /YT:
    post:
      operationId: yt_get_content_YT_post
      summary: Generate YouTube content
      responses:
        "200":
          description: OK
  /post/x:
    post:
      operationId: x_post_post_x_post
      summary: Post to X
      responses:
        "200":
          description: OK
        """,
        encoding="utf-8",
    )

    targets_path = tmp_path / "targets.json"
    targets_path.write_text(
        json.dumps(
            [
                {"name": "hello_work", "base_url": "http://127.0.0.1:8000", "openapi_spec_path": str(spec_path), "enabled": True},
                {"name": "hello_world", "base_url": "http://127.0.0.1:8001", "openapi_spec_path": str(spec_path), "enabled": True},
                {"name": "hello_world_love", "base_url": "http://127.0.0.1:8002", "openapi_spec_path": str(spec_path), "enabled": True},
            ],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    settings = Settings(
        target_registry_path=str(targets_path),
        report_output_dir=str(tmp_path / "reports"),
        testcase_generator_mode="ai",
        langchain_model_name="openai:gpt-5.2",
        langgraph_checkpointer="memory",
        langgraph_sqlite_path=str(tmp_path / "checkpoints.db"),
        http_timeout_seconds=10,
        sqlite_path=str(tmp_path / "runs.sqlite3"),
    )

    orchestrator = TestOrchestrator(
        settings,
        ai_agent=FakeAITestCaseAgent(),
        target_resolution_agent=FakeTargetResolutionAgent(),
        scope_resolution_agent=FakeScopeResolutionAgent(),
        feedback_scope_agent=FakeFeedbackScopeAgent(),
        understanding_service=FakeUnderstandingServiceSpecificImage(),
    )

    start_result = orchestrator.start_review_from_text(
        "test chức năng sinh ảnh của hello",
        thread_id="thread-feedback-ai-first",
    )
    assert start_result.status == "pending_target_selection"

    round1 = orchestrator.resume_target_selection(
        "thread-feedback-ai-first",
        selection="2",
    )
    assert round1.status == "pending_review"
    assert "POST /img" in round1.preview_text
    assert "POST /FB" not in round1.preview_text
    assert "POST /YT" not in round1.preview_text

    round2 = orchestrator.resume_review(
        "thread-feedback-ai-first",
        action="revise",
        feedback="thêm chức năng yt và fb",
    )
    assert "POST /img" in round2.preview_text
    assert "POST /FB" in round2.preview_text
    assert "POST /YT" in round2.preview_text

    round3 = orchestrator.resume_review(
        "thread-feedback-ai-first",
        action="revise",
        feedback="bỏ YT với FB đi",
    )
    assert "POST /img" in round3.preview_text
    assert "POST /FB" not in round3.preview_text
    assert "POST /YT" not in round3.preview_text