import json
from pathlib import Path

from api_testing_agent.config import Settings
from api_testing_agent.core.request_understanding_service import (
    InvalidFunctionRequestError,
    ResolvedPlan,
    UnderstandingResult,
)
from api_testing_agent.core.models import TestType
from api_testing_agent.tasks.orchestrator import TestOrchestrator


class FakeUnderstandingServiceAllScope:
    def understand(
        self,
        raw_text: str,
        *,
        forced_target_name: str,
        operation_hints: list[dict],
    ):
        plan = ResolvedPlan(
            target_name=forced_target_name,
            tags=[],
            methods=[],
            paths=[],
            test_types=[
                TestType.POSITIVE,
                TestType.MISSING_REQUIRED,
                TestType.INVALID_TYPE_OR_FORMAT,
                TestType.UNAUTHORIZED,
                TestType.NOT_FOUND,
            ],
            ignore_fields=[],
            limit_endpoints=50,
        )
        return UnderstandingResult(
            original_text=raw_text,
            canonical_command=f"test target {forced_target_name}",
            plan=plan,
        )


class FakeUnderstandingServiceInvalidFunction:
    def understand(
        self,
        raw_text: str,
        *,
        forced_target_name: str,
        operation_hints: list[dict],
    ):
        raise InvalidFunctionRequestError(
            f"Không tìm thấy chức năng 'payment' trong target '{forced_target_name}'.",
            available_functions=[
                "POST /img — Generate image",
                "POST /FB — Generate Facebook content",
            ],
        )


class FakeAITestCaseAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def generate_for_operation(self, context):
        from api_testing_agent.core.ai_testcase_models import AITestCaseDraft, AITestCaseDraftList

        method = context["operation"]["method"]
        path = context["operation"]["path"]

        return AITestCaseDraftList(
            cases=[
                AITestCaseDraft(
                    test_type="positive",
                    description=f"Positive case for {method} {path}",
                    reasoning_summary="Generated by fake test agent",
                    expected_status_codes=[200],
                )
            ]
        )


class FakeTargetDisambiguationAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def decide(self, *, raw_text: str, candidate_payload: list[dict]):
        from api_testing_agent.core.target_disambiguation_models import (
            TargetCandidate,
            TargetDisambiguationDecision,
        )

        return TargetDisambiguationDecision(
            mode="ask_user",
            selected_target=None,
            candidates=[
                TargetCandidate(name=item["name"], reason=item["reason"])
                for item in candidate_payload
            ],
            question="Bạn muốn chọn target nào?",
        )


class FakeScopeResolutionAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name


def test_general_request_after_target_selection_tests_all_scope(tmp_path: Path):
    spec_path = tmp_path / "openapi.yaml"
    spec_path.write_text(
        """
openapi: 3.0.0
info:
  title: Demo API
  version: 1.0.0

paths:
  /img:
    post:
      summary: Generate image
      responses:
        "200":
          description: OK
  /FB:
    post:
      summary: Generate Facebook content
      responses:
        "200":
          description: OK
  /YT:
    post:
      summary: Generate YouTube content
      responses:
        "200":
          description: OK
        """,
        encoding="utf-8",
    )

    targets_path = tmp_path / "targets.json"
    targets_path.write_text(
        json.dumps(
            [
                {
                    "name": "hello_work",
                    "base_url": "http://127.0.0.1:8000",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                },
                {
                    "name": "hello_world",
                    "base_url": "http://127.0.0.1:8001",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                },
                {
                    "name": "hello_world_love",
                    "base_url": "http://127.0.0.1:8002",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                },
            ],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    settings = Settings(
        target_registry_path=str(targets_path),
        report_output_dir=str(tmp_path / "reports"),
        testcase_generator_mode="ai",
        langchain_model_name="openai:gpt-5.2",
        langgraph_checkpointer="memory",
        langgraph_sqlite_path=str(tmp_path / "checkpoints.db"),
        http_timeout_seconds=10,
        sqlite_path=str(tmp_path / "runs.sqlite3"),
    )

    orchestrator = TestOrchestrator(
        settings,
        ai_agent=FakeAITestCaseAgent(),
        target_disambiguation_agent=FakeTargetDisambiguationAgent(),
        scope_resolution_agent=FakeScopeResolutionAgent(),
        understanding_service=FakeUnderstandingServiceAllScope(),
    )

    start_result = orchestrator.start_review_from_text(
        "hãy test hello cho tôi",
        thread_id="thread-all-scope",
    )

    assert start_result.status == "pending_target_selection"

    select_result = orchestrator.resume_target_selection(
        "thread-all-scope",
        selection="2",
    )

    assert select_result.status == "pending_review"
    assert select_result.selected_target == "hello_world"
    assert select_result.canonical_command == "test target hello_world"
    assert select_result.preview_text is not None
    assert "POST /img" in select_result.preview_text
    assert "POST /FB" in select_result.preview_text
    assert "POST /YT" in select_result.preview_text


def test_invalid_function_after_target_selection_returns_available_functions(tmp_path: Path):
    spec_path = tmp_path / "openapi.yaml"
    spec_path.write_text(
        """
openapi: 3.0.0
info:
  title: Demo API
  version: 1.0.0

paths:
  /img:
    post:
      summary: Generate image
      responses:
        "200":
          description: OK
  /FB:
    post:
      summary: Generate Facebook content
      responses:
        "200":
          description: OK
        """,
        encoding="utf-8",
    )

    targets_path = tmp_path / "targets.json"
    targets_path.write_text(
        json.dumps(
            [
                {
                    "name": "hello_world",
                    "base_url": "http://127.0.0.1:8001",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                }
            ],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    settings = Settings(
        target_registry_path=str(targets_path),
        report_output_dir=str(tmp_path / "reports"),
        testcase_generator_mode="ai",
        langchain_model_name="openai:gpt-5.2",
        langgraph_checkpointer="memory",
        langgraph_sqlite_path=str(tmp_path / "checkpoints.db"),
        http_timeout_seconds=10,
        sqlite_path=str(tmp_path / "runs.sqlite3"),
    )

    orchestrator = TestOrchestrator(
        settings,
        ai_agent=FakeAITestCaseAgent(),
        target_disambiguation_agent=None,
        scope_resolution_agent=FakeScopeResolutionAgent(),
        understanding_service=FakeUnderstandingServiceInvalidFunction(),
    )

    result = orchestrator.start_review_from_text(
        "hãy test chức năng payment của hello_world",
        thread_id="thread-invalid-function",
    )

    assert result.status == "invalid_function"
    assert result.selected_target == "hello_world"
    assert result.available_functions is not None
    assert "POST /img" in result.available_functions[0]