import json
from pathlib import Path

from api_testing_agent.config import Settings
from api_testing_agent.core.request_understanding_service import (
    ResolvedPlan,
    UnderstandingResult,
)
from api_testing_agent.core.models import TestType
from api_testing_agent.tasks.orchestrator import TestOrchestrator


class FakeUnderstandingServiceAllScope:
    def understand(
        self,
        raw_text: str,
        *,
        forced_target_name: str,
        operation_hints: list[dict],
    ):
        plan = ResolvedPlan(
            target_name=forced_target_name,
            tags=[],
            methods=[],
            paths=[],
            test_types=[
                TestType.POSITIVE,
                TestType.MISSING_REQUIRED,
                TestType.INVALID_TYPE_OR_FORMAT,
                TestType.UNAUTHORIZED,
                TestType.NOT_FOUND,
            ],
            ignore_fields=[],
            limit_endpoints=50,
        )
        return UnderstandingResult(
            original_text=raw_text,
            canonical_command=f"test target {forced_target_name} positive unauthorized not_found missing invalid",
            plan=plan,
        )


class FakeAITestCaseAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def generate_for_operation(self, context):
        from api_testing_agent.core.ai_testcase_models import AITestCaseDraft, AITestCaseDraftList

        op = context["operation"]
        return AITestCaseDraftList(
            cases=[
                AITestCaseDraft(
                    test_type="positive",
                    description=f"Positive case for {op['method']} {op['path']}",
                    reasoning_summary="Generated by fake AI agent",
                    expected_status_codes=[200],
                )
            ]
        )


class FakeTargetDisambiguationAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def decide(self, *, raw_text: str, candidate_payload: list[dict]):
        from api_testing_agent.core.target_disambiguation_models import (
            TargetCandidate,
            TargetDisambiguationDecision,
        )

        return TargetDisambiguationDecision(
            mode="ask_user",
            selected_target=None,
            candidates=[
                TargetCandidate(name=item["name"], reason=item["reason"])
                for item in candidate_payload
            ],
            question="Bạn muốn chọn target nào?",
        )


class FakeScopeResolutionAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name


class FakeFeedbackScopeAgent:
    def __init__(self) -> None:
        self._model_name = "fake:model"

    def set_model_name(self, model_name: str) -> None:
        self._model_name = model_name

    def decide(self, *, feedback_text: str, target_name: str, all_operation_hints: list[dict], current_scope_hints: list[dict]):
        from api_testing_agent.core.feedback_scope_models import FeedbackScopeDecision

        lowered = feedback_text.lower()

        if "chỉ test sinh ảnh" in lowered or "chi test sinh anh" in lowered:
            return FeedbackScopeDecision(
                action_mode="replace_with_specific",
                matched_operation_ids=["image_generate_img_post"],
                reason="Replace current scope with image generation only.",
            )

        if "thêm post bài" in lowered:
            return FeedbackScopeDecision(
                action_mode="add_specific",
                matched_paths=["/post/x"],
                reason="Add post/x to current scope.",
            )

        if "bỏ yt với fb đi" in lowered or "bỏ youtube với facebook đi" in lowered:
            return FeedbackScopeDecision(
                action_mode="remove_specific",
                matched_paths=["/YT", "/FB"],
                reason="Remove YT and FB operations from current scope.",
            )

        if "test lại toàn bộ" in lowered or "quay lại toàn bộ" in lowered:
            return FeedbackScopeDecision(
                action_mode="reset_all",
                reason="Reset back to full scope.",
            )

        return FeedbackScopeDecision(
            action_mode="keep",
            reason="No scope change.",
        )


def test_feedback_can_replace_add_and_remove_scope(tmp_path: Path):
    spec_path = tmp_path / "openapi.yaml"
    spec_path.write_text(
        """
openapi: 3.0.0
info:
  title: Demo API
  version: 1.0.0

paths:
  /img:
    post:
      operationId: image_generate_img_post
      summary: Generate image
      responses:
        "200":
          description: OK
  /FB:
    post:
      operationId: fb_get_content_FB_post
      summary: Generate Facebook content
      responses:
        "200":
          description: OK
  /YT:
    post:
      operationId: yt_get_content_YT_post
      summary: Generate YouTube content
      responses:
        "200":
          description: OK
  /post/x:
    post:
      operationId: x_post_post_x_post
      summary: Post to X
      responses:
        "200":
          description: OK
        """,
        encoding="utf-8",
    )

    targets_path = tmp_path / "targets.json"
    targets_path.write_text(
        json.dumps(
            [
                {
                    "name": "hello_work",
                    "base_url": "http://127.0.0.1:8000",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                },
                {
                    "name": "hello_world",
                    "base_url": "http://127.0.0.1:8001",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                },
                {
                    "name": "hello_world_love",
                    "base_url": "http://127.0.0.1:8002",
                    "openapi_spec_path": str(spec_path),
                    "enabled": True,
                },
            ],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    settings = Settings(
        target_registry_path=str(targets_path),
        report_output_dir=str(tmp_path / "reports"),
        testcase_generator_mode="ai",
        langchain_model_name="openai:gpt-5.2",
        langgraph_checkpointer="memory",
        langgraph_sqlite_path=str(tmp_path / "checkpoints.db"),
        http_timeout_seconds=10,
        sqlite_path=str(tmp_path / "runs.sqlite3"),
    )

    orchestrator = TestOrchestrator(
        settings,
        ai_agent=FakeAITestCaseAgent(),
        target_disambiguation_agent=FakeTargetDisambiguationAgent(),
        scope_resolution_agent=FakeScopeResolutionAgent(),
        understanding_service=FakeUnderstandingServiceAllScope(),
    )

    # inject fake feedback scope agent vào refiner
    orchestrator._feedback_scope_agent = FakeFeedbackScopeAgent()
    from api_testing_agent.core.feedback_scope_refiner import FeedbackScopeRefiner
    orchestrator._feedback_scope_refiner = FeedbackScopeRefiner(orchestrator._feedback_scope_agent)
    from api_testing_agent.core.testcase_review_graph import build_testcase_review_graph
    orchestrator._review_graph = build_testcase_review_graph(
        agent=orchestrator._ai_agent,
        draft_reporter=orchestrator._draft_reporter,
        feedback_scope_refiner=orchestrator._feedback_scope_refiner,
        checkpointer=orchestrator._checkpointer,
    )

    start_result = orchestrator.start_review_from_text(
        "test hello cho tôi",
        thread_id="thread-feedback-complex",
    )
    assert start_result.status == "pending_target_selection"

    round1 = orchestrator.resume_target_selection(
        "thread-feedback-complex",
        selection="1",
    )
    assert round1.status == "pending_review"
    assert "POST /img" in round1.preview_text
    assert "POST /FB" in round1.preview_text
    assert "POST /YT" in round1.preview_text
    assert "POST /post/x" in round1.preview_text

    round2 = orchestrator.resume_review(
        "thread-feedback-complex",
        action="revise",
        feedback="chỉ test sinh ảnh",
    )
    assert "POST /img" in round2.preview_text
    assert "POST /FB" not in round2.preview_text
    assert "POST /YT" not in round2.preview_text
    assert "POST /post/x" not in round2.preview_text

    round3 = orchestrator.resume_review(
        "thread-feedback-complex",
        action="revise",
        feedback="thêm post bài nữa",
    )
    assert "POST /img" in round3.preview_text
    assert "POST /post/x" in round3.preview_text
    assert "POST /FB" not in round3.preview_text
    assert "POST /YT" not in round3.preview_text

    round4 = orchestrator.resume_review(
        "thread-feedback-complex",
        action="revise",
        feedback="bỏ YT với FB đi",
    )
    assert "POST /img" in round4.preview_text
    assert "POST /post/x" in round4.preview_text
    assert "POST /FB" not in round4.preview_text
    assert "POST /YT" not in round4.preview_text

    round5 = orchestrator.resume_review(
        "thread-feedback-complex",
        action="revise",
        feedback="test lại toàn bộ",
    )
    assert "POST /img" in round5.preview_text
    assert "POST /FB" in round5.preview_text
    assert "POST /YT" in round5.preview_text
    assert "POST /post/x" in round5.preview_text